# fly.toml app configuration file generated for telegram-twitter-bot

app = "telegram-twitter-bot"
primary_region = "hkg"

[build]
dockerfile = "Dockerfile"

[processes]
app = "python bot.py"

[[vm]]
size = "shared-cpu-1x"
memory = "256mb"

[env]
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"

# Health check configuration (optional for background services)
[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 1